stages:
  - sonarqube-check

sonarqube-check:
  stage: sonarqube-check
  only:
    - main
    - staging
  variables:
    SONAR_HOST_URL: 'https://sonarqube.cs.ui.ac.id/'
    GIT_DEPTH: 0
  script: gradle sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
